title: NSExtension Mappings Command
description: This command returns information about installed extensions for a user.
payload:
  requesttype: NSExtensionMappings
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: '10.13'
      accessrights: QueryInstalledApps
      devicechannel: false
      userchannel: true
      requiresdep: false
      userenrollment:
        mode: forbidden
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  content: |-
    This command returns information about installed extensions for a user.
    The purpose of this command is to allow the server to build a mapping of
    extension identifiers to extension points to provide a UI for generating
    "com.apple.NSExtension" payloads.
    Requires "Query Installed Apps" right; supported on user channel only
responsekeys:
- key: Extensions
  type: <array>
  presence: required
  content: An array of dictionaries that contains information about extensions on
    the device.
  subkeys:
  - key: ExtensionsItem
    type: <dictionary>
    subkeys:
    - key: Identifier
      type: <string>
      presence: required
      content: The identifier of the extension.
    - key: ExtensionPoint
      type: <string>
      presence: required
      content: The NSExtensionPointIdentifier for the extension.
    - key: DisplayName
      type: <string>
      presence: required
      content: The display name of the extension.
