title: Install Enterprise Application Command
description: This command allows the server to install enterprise applications on
  a device. It provides a more secure version of 'InstallApplication' that specifies
  a 'ManifestURL'.
payload:
  requesttype: InstallEnterpriseApplication
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: 10.13.6
      accessrights: AllowAppInstallation
      devicechannel: true
      userchannel: false
      requiresdep: false
      userenrollment:
        mode: allowed
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  content: This command allows the server to install an application on a device. It
    provides a more secure version of 'InstallApplication' that specifies a 'ManifestURL'.
payloadkeys:
- key: Manifest
  type: <dictionary>
  presence: optional
  content: A dictionary that specifies where to download the app. This value is backward-compatible
    with the manifest for the InstallApplicationCommand; however, it also allows you
    to specify 'sha256s' and 'sha256-size' for SHA-256 hashes.
  subkeys:
  - key: ANY
    type: <any>
    presence: optional
    content: A manifest, which is backward-compatible with the manifest for the 'InstallApplication'
      command; however, it also allows you to specify 'sha256s' and 'sha256-size'
      for SHA-256 hashes.
- key: ManifestURL
  type: <string>
  presence: optional
  content: The URL of the app manifest, which needs to begin with 'https:'. The manifest
    is returned as a property list.
- key: ManifestURLPinningCerts
  type: <array>
  presence: optional
  content: An array of DER-encoded certificates to pin the connection when fetching
    the 'ManifestURL'.
  subkeys:
  - key: ManifestURLPinningCertsItem
    type: <data>
    presence: required
    content: A certificate in DER-encoded format.
- key: PinningRevocationCheckRequired
  type: <boolean>
  presence: optional
  default: false
  content: If 'true', certificate revocation checks require a positive response when
    using certificate pinning with 'ManifestURLPinningCerts'.
- key: InstallAsManaged
  supportedOS:
    macOS:
      introduced: '11.0'
      userenrollment:
        mode: forbidden
  type: <boolean>
  presence: optional
  default: false
  content: |-
    If 'true', install the app as a managed app. Otherwise, the system installs the app as unmanaged. If you reinstall a manged app and omit this value or set it to 'false', the app becomes unmanaged.
    For manifest-based installs, if 'true', the system only considers apps installed in '/Applications' as managed. In macOS 11 through 13, the system requires that the 'pkg' only contains a single signed app.
    Available in macOS 11 and later.
- key: ManagementFlags
  supportedOS:
    macOS:
      introduced: '11.0'
      userenrollment:
        mode: forbidden
  type: <integer>
  presence: optional
  rangelist:
  - 1
  content: |-
    The management flags. The possible values are:

    * '1': If 'InstallAsManaged' is 'true', remove the app upon removal of the MDM profile.

    Available in macOS 11 and later.
- key: Configuration
  supportedOS:
    macOS:
      introduced: '11.0'
  type: <dictionary>
  presence: optional
  content: A dictionary that contains the initial configuration of the app, if you
    choose to provide it. Available in macOS 11 and later.
  subkeys:
  - key: ANY
    type: <any>
    presence: optional
    content: An app configuration.
- key: ChangeManagementState
  supportedOS:
    macOS:
      introduced: '11.0'
      userenrollment:
        mode: forbidden
  type: <string>
  presence: optional
  rangelist:
  - Managed
  content: |-
    The change management state. This value doesn't work with the User Enrollment feature introduced in iOS 13. The only possible value is:

    * 'Managed': Take management of the app if the user installed it already and 'InstallAsManaged' is 'true'.

    Available in macOS 11 and later.
- key: iOSApp
  supportedOS:
    iOS:
      introduced: n/a
    macOS:
      introduced: '11.0'
    tvOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: false
  content: If 'true', the app is an iOS app that can run on an Apple silicon in macOS
    11 and later.
