title: Managed Application Configuration Command
description: This command queries the device for the current configuration of managed
  applications. This command requires the App Management right. macOS supports this
  command as of 10.15, on the device channel and for User Enrollments only, because
  Settings->ApplicationConfiguration is supported. Since macOS does not support Managed
  Applications, this command can be used for any bundle identifier.
payload:
  requesttype: ManagedApplicationConfiguration
  supportedOS:
    iOS:
      introduced: '7.0'
      accessrights: AllowAppInstallation
      supervised: false
      requiresdep: false
      sharedipad:
        mode: allowed
        devicechannel: true
        userchannel: false
      userenrollment:
        mode: allowed
    macOS:
      introduced: '10.15'
      accessrights: AllowAppInstallation
      devicechannel: true
      userchannel: false
      requiresdep: false
      userenrollment:
        mode: allowed
    tvOS:
      introduced: '10.2'
      accessrights: AllowAppInstallation
      supervised: false
    visionOS:
      introduced: '1.1'
      accessrights: AllowAppInstallation
      supervised: false
      requiresdep: false
      userenrollment:
        mode: allowed
    watchOS:
      introduced: '10.0'
      accessrights: AllowAppInstallation
      supervised: false
  content: This command queries the device for the current configuration of managed
    applications. This command requires the App Management right. The response will
    not include apps that are managed by Declarative Device Management.
payloadkeys:
- key: Identifiers
  type: <array>
  presence: required
  content: |-
    The bundle identifiers of the managed apps.
    For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired. Obtain the watch's bundle identifier for an app with a watch bundle, in the 'watchBundleId' key that's part of the Content Metadata query. For more information on this query, see Getting App and Book Information (Legacy).
  subkeys:
  - key: IdentifiersItem
    type: <string>
responsekeys:
- key: ApplicationConfigurations
  type: <array>
  presence: required
  content: An array of app configurations items.
  subkeys:
  - key: ApplicationConfigurationsItem
    type: <dictionary>
    subkeys:
    - key: Identifier
      type: <string>
      presence: required
      content: |-
        The app's bundle identifier.
        For a watchOS app, the identifier is the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired.
    - key: Configuration
      type: <dictionary>
      presence: optional
      content: The app's configurations.
      subkeys:
      - key: ANY
        type: <any>
        presence: optional
        content: The app's configuration items.
